// <auto-generated />
using System;
using GIPManager;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GIPManager.Migrations
{
    [DbContext(typeof(StoreContext))]
    [Migration("20190408034736_DeviceMaterials")]
    partial class DeviceMaterials
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GIPManager.ActionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("ActionTypes");
                });

            modelBuilder.Entity("GIPManager.AdditionalMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DeviceId");

                    b.Property<int>("MaterialId");

                    b.Property<double>("Volume");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("MaterialId");

                    b.ToTable("AdditionalMaterials");
                });

            modelBuilder.Entity("GIPManager.CommentRegPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("RegPointId");

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.HasIndex("RegPointId");

                    b.ToTable("CommentRegPoints");
                });

            modelBuilder.Entity("GIPManager.CommentSubstation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<int>("SubstationId");

                    b.Property<string>("Text");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("SubstationId");

                    b.HasIndex("UserId");

                    b.ToTable("CommentSubstations");
                });

            modelBuilder.Entity("GIPManager.Consumer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContractNumber");

                    b.Property<string>("Name");

                    b.Property<string>("O_Build");

                    b.Property<string>("O_Flat");

                    b.Property<string>("O_House");

                    b.Property<string>("O_Index");

                    b.Property<string>("O_Local");

                    b.Property<string>("O_Local_Secondary");

                    b.Property<string>("O_Street");

                    b.Property<int>("RegPointId");

                    b.Property<string>("U_Build");

                    b.Property<string>("U_Flat");

                    b.Property<string>("U_House");

                    b.Property<string>("U_Index");

                    b.Property<string>("U_Local");

                    b.Property<string>("U_Local_Secondary");

                    b.Property<string>("U_Street");

                    b.HasKey("Id");

                    b.HasIndex("RegPointId")
                        .IsUnique();

                    b.ToTable("Consumers");
                });

            modelBuilder.Entity("GIPManager.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("GIPManager.DeliveryAct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ContractId");

                    b.Property<DateTime>("Date");

                    b.Property<int>("DeliveryStateId");

                    b.Property<int>("DeliveryTypeId");

                    b.Property<string>("SetName");

                    b.Property<int>("UserId");

                    b.Property<int?>("WorkerId");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("DeliveryStateId");

                    b.HasIndex("DeliveryTypeId");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkerId");

                    b.ToTable("DeliveryActs");
                });

            modelBuilder.Entity("GIPManager.DeliveryState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("DeliveryStates");
                });

            modelBuilder.Entity("GIPManager.DeliveryType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("DeliveryTypes");
                });

            modelBuilder.Entity("GIPManager.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ContractId");

                    b.Property<string>("CurrentState");

                    b.Property<int>("DeviceTypeId");

                    b.Property<int?>("KDEId");

                    b.Property<string>("SerialNumber")
                        .IsRequired();

                    b.Property<int?>("SetId");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("DeviceTypeId");

                    b.HasIndex("KDEId");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("GIPManager.DeviceDelivery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment");

                    b.Property<int>("DeliveryActId");

                    b.Property<int?>("DeviceId");

                    b.Property<int?>("DeviceTypeId");

                    b.Property<string>("SerialNumber");

                    b.Property<int?>("SetId");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryActId");

                    b.HasIndex("DeviceId");

                    b.HasIndex("DeviceTypeId");

                    b.ToTable("DeviceDeliveries");
                });

            modelBuilder.Entity("GIPManager.DeviceMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DeviceId");

                    b.Property<int>("MaterialId");

                    b.Property<double>("Volume");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("MaterialId");

                    b.ToTable("DeviceMaterials");
                });

            modelBuilder.Entity("GIPManager.DeviceState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment");

                    b.Property<DateTime>("Date");

                    b.Property<int>("DeviceId");

                    b.Property<int>("DeviceStateTypeId");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("DeviceStateTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("DeviceStates");
                });

            modelBuilder.Entity("GIPManager.DeviceStateType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.HasKey("Id");

                    b.ToTable("DeviceStateTypes");
                });

            modelBuilder.Entity("GIPManager.DeviceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccuracyClass")
                        .HasMaxLength(10);

                    b.Property<string>("Description")
                        .HasMaxLength(500);

                    b.Property<string>("EnergyType")
                        .HasMaxLength(10);

                    b.Property<string>("INom")
                        .HasMaxLength(10);

                    b.Property<string>("ModelCode")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<double>("Price");

                    b.Property<int>("TestInterval");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("UNom")
                        .HasMaxLength(10);

                    b.HasKey("Id");

                    b.ToTable("DeviceTypes");
                });

            modelBuilder.Entity("GIPManager.EmploymentContract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<string>("Number");

                    b.Property<int>("WorkerId");

                    b.HasKey("Id");

                    b.HasIndex("WorkerId");

                    b.ToTable("EmploymentContracts");
                });

            modelBuilder.Entity("GIPManager.InstallAct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Feeder");

                    b.Property<int>("InstallActType");

                    b.Property<int?>("InstallPlaceNumber");

                    b.Property<int>("InstallPlaceTypeId");

                    b.Property<bool>("IsCommReg");

                    b.Property<bool>("IsOutFlow");

                    b.Property<string>("Line");

                    b.Property<string>("PS");

                    b.Property<int>("RegPointId");

                    b.Property<string>("Seal_AV1");

                    b.Property<string>("Seal_AV2");

                    b.Property<string>("Seal_KDE");

                    b.Property<string>("Seal_KI");

                    b.Property<string>("Seal_RegDevice");

                    b.Property<string>("Seal_TT_A");

                    b.Property<string>("Seal_TT_B");

                    b.Property<string>("Seal_TT_C");

                    b.Property<string>("Section");

                    b.Property<string>("T1");

                    b.Property<string>("T2");

                    b.Property<string>("TT_A_Serial");

                    b.Property<string>("TT_B_Serial");

                    b.Property<string>("TT_C_Serial");

                    b.Property<string>("TT_Koefficient");

                    b.Property<string>("Tsum");

                    b.Property<string>("Uninstalled_Ktt");

                    b.Property<string>("Uninstalled_Serial");

                    b.Property<string>("Uninstalled_TSum");

                    b.HasKey("Id");

                    b.HasIndex("InstallPlaceTypeId");

                    b.HasIndex("RegPointId")
                        .IsUnique();

                    b.ToTable("InstallActs");
                });

            modelBuilder.Entity("GIPManager.InstallPlaceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("InstallPlaceTypes");
                });

            modelBuilder.Entity("GIPManager.KDE", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("KDETypeId");

                    b.Property<int?>("PowerLineSupportId");

                    b.HasKey("Id");

                    b.HasIndex("KDETypeId");

                    b.HasIndex("PowerLineSupportId");

                    b.ToTable("KDEs");
                });

            modelBuilder.Entity("GIPManager.KDEType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("KDETypes");
                });

            modelBuilder.Entity("GIPManager.Letter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateLetter");

                    b.Property<DateTime>("HandingDate");

                    b.Property<DateTime>("InviteDate");

                    b.Property<DateTime>("NotifyDate");

                    b.Property<string>("OutNumber");

                    b.Property<bool>("Printed");

                    b.Property<int>("RegPointId");

                    b.Property<string>("TrackNumber");

                    b.HasKey("Id");

                    b.HasIndex("RegPointId");

                    b.ToTable("Letters");
                });

            modelBuilder.Entity("GIPManager.Link", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DeviceId");

                    b.Property<string>("LinkType");

                    b.Property<string>("PhoneNumber");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("Links");
                });

            modelBuilder.Entity("GIPManager.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ContractId");

                    b.Property<int>("MaterialTypeId");

                    b.Property<double>("Volume");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("MaterialTypeId");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("GIPManager.MaterialDelivery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DeliveryActId");

                    b.Property<int?>("MaterialId");

                    b.Property<int>("MaterialTypeId");

                    b.Property<string>("Other");

                    b.Property<double>("Volume");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryActId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("MaterialTypeId");

                    b.ToTable("MaterialDeliveries");
                });

            modelBuilder.Entity("GIPManager.MaterialType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MaterialUnitId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<double>("Price");

                    b.HasKey("Id");

                    b.HasIndex("MaterialUnitId");

                    b.ToTable("MaterialTypes");
                });

            modelBuilder.Entity("GIPManager.MaterialUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.HasKey("Id");

                    b.ToTable("MaterialUnits");
                });

            modelBuilder.Entity("GIPManager.MounterReportUgesAL", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Brigade");

                    b.Property<int>("ContractId");

                    b.Property<int?>("CuratorId");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Fider");

                    b.Property<string>("Local");

                    b.Property<int>("NetRegionId");

                    b.Property<int>("ReportStateId");

                    b.Property<string>("Substation");

                    b.Property<string>("WorkPermit");

                    b.Property<int>("WorkerId");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("NetRegionId");

                    b.HasIndex("ReportStateId");

                    b.HasIndex("WorkerId");

                    b.ToTable("MounterReportUgesALs");
                });

            modelBuilder.Entity("GIPManager.MounterReportUgesDeviceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Building");

                    b.Property<int>("DeviceId");

                    b.Property<string>("DeviceSeal");

                    b.Property<int>("ErrorCode");

                    b.Property<string>("Flat");

                    b.Property<string>("House");

                    b.Property<string>("InstallPlace");

                    b.Property<int?>("KDEId");

                    b.Property<string>("KDESeal");

                    b.Property<string>("KDEType");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("PowerLineType");

                    b.Property<string>("Serial");

                    b.Property<string>("Street");

                    b.Property<double>("Sum");

                    b.Property<string>("SwitchSeal");

                    b.Property<double>("T1");

                    b.Property<double>("T2");

                    b.Property<double>("U1");

                    b.Property<double>("U2");

                    b.Property<double>("U3");

                    b.Property<double>("WireConsumptionNewInput");

                    b.Property<double>("WireConsumptionUpDown");

                    b.Property<int>("WorkerId");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("KDEId");

                    b.HasIndex("WorkerId");

                    b.ToTable("MounterReportUgesALItems");
                });

            modelBuilder.Entity("GIPManager.NetRegion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ChiefName");

                    b.Property<string>("ContactName");

                    b.Property<int>("ContractId");

                    b.Property<string>("Email");

                    b.Property<string>("FullName");

                    b.Property<string>("Name");

                    b.Property<string>("PhoneNumber");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.ToTable("NetRegions");
                });

            modelBuilder.Entity("GIPManager.NetRegionAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActionTypeId");

                    b.Property<string>("Comment");

                    b.Property<DateTime>("Date");

                    b.Property<int>("NetRegionId");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("ActionTypeId");

                    b.HasIndex("NetRegionId");

                    b.HasIndex("UserId");

                    b.ToTable("NetRegionActions");
                });

            modelBuilder.Entity("GIPManager.PPE", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int>("Volume");

                    b.HasKey("Id");

                    b.ToTable("PPEs");
                });

            modelBuilder.Entity("GIPManager.PPEDelivery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DeliveryActId");

                    b.Property<int?>("PPEId");

                    b.Property<int>("Volume");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryActId");

                    b.HasIndex("PPEId")
                        .IsUnique()
                        .HasFilter("[PPEId] IS NOT NULL");

                    b.ToTable("PPEDeliveries");
                });

            modelBuilder.Entity("GIPManager.PaymentReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment");

                    b.Property<DateTime>("DateCreate");

                    b.Property<DateTime>("DatePeriodStart");

                    b.Property<bool>("IsClosed");

                    b.Property<int>("WorkerId");

                    b.HasKey("Id");

                    b.HasIndex("WorkerId");

                    b.ToTable("PaymentReports");
                });

            modelBuilder.Entity("GIPManager.PaymentReportRegPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("CostRUB");

                    b.Property<int>("PaymentReportId");

                    b.Property<int>("RegPointId");

                    b.Property<int>("WorkType");

                    b.HasKey("Id");

                    b.HasIndex("PaymentReportId");

                    b.HasIndex("RegPointId");

                    b.ToTable("PaymentReportRegPoints");
                });

            modelBuilder.Entity("GIPManager.PowerLineSupport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FixatorsCount");

                    b.Property<int>("MounterReportUgesALId");

                    b.Property<string>("PowerLineType");

                    b.Property<int>("SupportNumber");

                    b.HasKey("Id");

                    b.HasIndex("MounterReportUgesALId");

                    b.ToTable("PowerLineSupports");
                });

            modelBuilder.Entity("GIPManager.RegPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DeviceId");

                    b.Property<int>("Status");

                    b.Property<int>("SubstationId");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("SubstationId");

                    b.ToTable("RegPoints");
                });

            modelBuilder.Entity("GIPManager.RegPointAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActionTypeId");

                    b.Property<string>("Comment");

                    b.Property<DateTime>("Date");

                    b.Property<int>("RegPointId");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("ActionTypeId");

                    b.HasIndex("RegPointId");

                    b.HasIndex("UserId");

                    b.ToTable("RegPointActions");
                });

            modelBuilder.Entity("GIPManager.RegPointFlags", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("ExsistRegDevice");

                    b.Property<bool>("ImportConsummerData");

                    b.Property<bool>("IsAscueChecked");

                    b.Property<bool>("IsAscueOk");

                    b.Property<bool>("IsLinkOk");

                    b.Property<bool>("IsReplace");

                    b.Property<int>("RegPointId");

                    b.Property<bool>("ReportedByMounter");

                    b.HasKey("Id");

                    b.HasIndex("RegPointId")
                        .IsUnique();

                    b.ToTable("RegPointFlags");
                });

            modelBuilder.Entity("GIPManager.ReportComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<int>("ReportId");

                    b.Property<int>("ReportTypeId");

                    b.Property<string>("Text");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("ReportTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("ReportComments");
                });

            modelBuilder.Entity("GIPManager.ReportRemark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ReportId");

                    b.Property<int>("ReportTypeId");

                    b.Property<string>("Text");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("ReportTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("ReportRemarks");
                });

            modelBuilder.Entity("GIPManager.ReportState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.HasKey("Id");

                    b.ToTable("ReportStates");
                });

            modelBuilder.Entity("GIPManager.ReportType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.HasKey("Id");

                    b.ToTable("ReportTypes");
                });

            modelBuilder.Entity("GIPManager.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("GIPManager.SBReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Brigade");

                    b.Property<int>("ContractId");

                    b.Property<int?>("CuratorId");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Local");

                    b.Property<string>("MeterBoard");

                    b.Property<int>("NetRegionId");

                    b.Property<string>("Phase");

                    b.Property<string>("PhoneNumber");

                    b.Property<int>("ReportStateId");

                    b.Property<string>("Substation");

                    b.Property<string>("WorkPermit");

                    b.Property<int>("WorkerId");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("NetRegionId");

                    b.HasIndex("ReportStateId");

                    b.HasIndex("WorkerId");

                    b.ToTable("SBReports");
                });

            modelBuilder.Entity("GIPManager.Substation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsBalanceDone");

                    b.Property<bool>("IsInstallationDone");

                    b.Property<bool>("IsPropSchemeDone");

                    b.Property<string>("Name");

                    b.Property<int>("NetRegionId");

                    b.Property<int>("SubstationStateId");

                    b.HasKey("Id");

                    b.HasIndex("NetRegionId");

                    b.HasIndex("SubstationStateId");

                    b.ToTable("Substations");
                });

            modelBuilder.Entity("GIPManager.SubstationAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActionTypeId");

                    b.Property<string>("Comment");

                    b.Property<DateTime>("Date");

                    b.Property<int>("SubstationId");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("ActionTypeId");

                    b.HasIndex("SubstationId");

                    b.HasIndex("UserId");

                    b.ToTable("SubstationActions");
                });

            modelBuilder.Entity("GIPManager.SubstationDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DeviceId");

                    b.Property<int>("SubstationId");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("SubstationId");

                    b.ToTable("SubstationDevices");
                });

            modelBuilder.Entity("GIPManager.SubstationLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PhoneNumber");

                    b.Property<int>("SubstationId");

                    b.HasKey("Id");

                    b.HasIndex("SubstationId");

                    b.ToTable("SubstationLinks");
                });

            modelBuilder.Entity("GIPManager.SubstationState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("SubstationStates");
                });

            modelBuilder.Entity("GIPManager.Switch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DeviceSeal");

                    b.Property<string>("DeviceSerial");

                    b.Property<int>("ErrorCode");

                    b.Property<int?>("SBReportId");

                    b.Property<double>("Sum");

                    b.Property<string>("SwitchNumber");

                    b.Property<string>("SwitchType");

                    b.Property<double>("T1");

                    b.Property<double>("T2");

                    b.Property<string>("TTANumber");

                    b.Property<string>("TTASeal");

                    b.Property<int>("TTAk");

                    b.Property<string>("TTBNumber");

                    b.Property<string>("TTBSeal");

                    b.Property<int>("TTBk");

                    b.Property<string>("TTCNumber");

                    b.Property<string>("TTCSeal");

                    b.Property<int>("TTCk");

                    b.Property<string>("TestBoxSeal");

                    b.Property<int?>("USPDReportId");

                    b.HasKey("Id");

                    b.HasIndex("SBReportId");

                    b.HasIndex("USPDReportId");

                    b.ToTable("Switches");
                });

            modelBuilder.Entity("GIPManager.USPDReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AVR");

                    b.Property<string>("Brigade");

                    b.Property<int>("ContractId");

                    b.Property<int?>("CuratorId");

                    b.Property<DateTime>("Date");

                    b.Property<double>("Ftp");

                    b.Property<double>("Gofr");

                    b.Property<double>("Kvvg");

                    b.Property<string>("Local");

                    b.Property<int>("NetRegionId");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("PlcSerial");

                    b.Property<int>("ReportStateId");

                    b.Property<string>("Substation");

                    b.Property<string>("UspdSerial");

                    b.Property<int>("WorkerId");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("NetRegionId");

                    b.HasIndex("ReportStateId");

                    b.HasIndex("WorkerId");

                    b.ToTable("USPDReports");
                });

            modelBuilder.Entity("GIPManager.UnmountReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ContractId");

                    b.Property<int?>("CuratorId");

                    b.Property<DateTime>("Date");

                    b.Property<int>("ReportStateId");

                    b.Property<int>("WorkerId");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("ReportStateId");

                    b.HasIndex("WorkerId");

                    b.ToTable("UnmountReports");
                });

            modelBuilder.Entity("GIPManager.UnmountedDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DeviceId");

                    b.Property<string>("Reason");

                    b.Property<int>("UnmountReportId");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("UnmountReportId");

                    b.ToTable("UnmountedDevices");
                });

            modelBuilder.Entity("GIPManager.UnreadSubstationComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CommentSubstationId");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CommentSubstationId");

                    b.HasIndex("UserId");

                    b.ToTable("UnreadSubstationComments");
                });

            modelBuilder.Entity("GIPManager.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("Login");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.Property<int?>("RoleId");

                    b.Property<int?>("WorkerID");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GIPManager.Worker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("DeliveryAvailible");

                    b.Property<string>("MIddlename")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .HasMaxLength(20);

                    b.Property<string>("Surname")
                        .HasMaxLength(50);

                    b.Property<int>("WorkerTypeId");

                    b.HasKey("Id");

                    b.HasIndex("WorkerTypeId");

                    b.ToTable("Workers");
                });

            modelBuilder.Entity("GIPManager.WorkerType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("WorkerTypes");
                });

            modelBuilder.Entity("GIPManager.AdditionalMaterial", b =>
                {
                    b.HasOne("GIPManager.Device", "Device")
                        .WithMany("AdditionalMaterials")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GIPManager.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GIPManager.CommentRegPoint", b =>
                {
                    b.HasOne("GIPManager.RegPoint", "RegPoint")
                        .WithMany("Comments")
                        .HasForeignKey("RegPointId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GIPManager.CommentSubstation", b =>
                {
                    b.HasOne("GIPManager.Substation", "Substation")
                        .WithMany("Comments")
                        .HasForeignKey("SubstationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GIPManager.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GIPManager.Consumer", b =>
                {
                    b.HasOne("GIPManager.RegPoint", "RegPoint")
                        .WithOne("Consumer")
                        .HasForeignKey("GIPManager.Consumer", "RegPointId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GIPManager.DeliveryAct", b =>
                {
                    b.HasOne("GIPManager.Contract", "Contract")
                        .WithMany("DeliveryActs")
                        .HasForeignKey("ContractId");

                    b.HasOne("GIPManager.DeliveryState", "DeliveryState")
                        .WithMany("DeliveryActs")
                        .HasForeignKey("DeliveryStateId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GIPManager.DeliveryType", "DeliveryType")
                        .WithMany("DeliveryActs")
                        .HasForeignKey("DeliveryTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GIPManager.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GIPManager.Worker", "Worker")
                        .WithMany("DeliveryActs")
                        .HasForeignKey("WorkerId");
                });

            modelBuilder.Entity("GIPManager.Device", b =>
                {
                    b.HasOne("GIPManager.Contract", "Contract")
                        .WithMany("Devices")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GIPManager.DeviceType", "DeviceType")
                        .WithMany("Devices")
                        .HasForeignKey("DeviceTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GIPManager.KDE", "KDE")
                        .WithMany("Devices")
                        .HasForeignKey("KDEId");
                });

            modelBuilder.Entity("GIPManager.DeviceDelivery", b =>
                {
                    b.HasOne("GIPManager.DeliveryAct", "DeliveryAct")
                        .WithMany("DeviceDeliveries")
                        .HasForeignKey("DeliveryActId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GIPManager.Device", "Device")
                        .WithMany("DeviceDeliveries")
                        .HasForeignKey("DeviceId");

                    b.HasOne("GIPManager.DeviceType", "DeviceType")
                        .WithMany()
                        .HasForeignKey("DeviceTypeId");
                });

            modelBuilder.Entity("GIPManager.DeviceMaterial", b =>
                {
                    b.HasOne("GIPManager.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GIPManager.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GIPManager.DeviceState", b =>
                {
                    b.HasOne("GIPManager.Device", "Device")
                        .WithMany("DeviceStates")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GIPManager.DeviceStateType", "DeviceStateType")
                        .WithMany()
                        .HasForeignKey("DeviceStateTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GIPManager.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GIPManager.EmploymentContract", b =>
                {
                    b.HasOne("GIPManager.Worker", "Worker")
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GIPManager.InstallAct", b =>
                {
                    b.HasOne("GIPManager.InstallPlaceType", "InstallPlaceType")
                        .WithMany()
                        .HasForeignKey("InstallPlaceTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GIPManager.RegPoint", "RegPoint")
                        .WithOne("InstallAct")
                        .HasForeignKey("GIPManager.InstallAct", "RegPointId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GIPManager.KDE", b =>
                {
                    b.HasOne("GIPManager.KDEType", "KDEType")
                        .WithMany()
                        .HasForeignKey("KDETypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GIPManager.PowerLineSupport", "PowerLineSupport")
                        .WithMany("KDEs")
                        .HasForeignKey("PowerLineSupportId");
                });

            modelBuilder.Entity("GIPManager.Letter", b =>
                {
                    b.HasOne("GIPManager.RegPoint", "RegPoint")
                        .WithMany("Letters")
                        .HasForeignKey("RegPointId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GIPManager.Link", b =>
                {
                    b.HasOne("GIPManager.Device", "Device")
                        .WithMany("Links")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GIPManager.Material", b =>
                {
                    b.HasOne("GIPManager.Contract", "Contract")
                        .WithMany("Materials")
                        .HasForeignKey("ContractId");

                    b.HasOne("GIPManager.MaterialType", "MaterialType")
                        .WithMany("Materials")
                        .HasForeignKey("MaterialTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GIPManager.MaterialDelivery", b =>
                {
                    b.HasOne("GIPManager.DeliveryAct", "DeliveryAct")
                        .WithMany("MaterialDeliveries")
                        .HasForeignKey("DeliveryActId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GIPManager.Material", "Material")
                        .WithMany("MaterialDeliveries")
                        .HasForeignKey("MaterialId");

                    b.HasOne("GIPManager.MaterialType", "MaterialType")
                        .WithMany()
                        .HasForeignKey("MaterialTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GIPManager.MaterialType", b =>
                {
                    b.HasOne("GIPManager.MaterialUnit", "Unit")
                        .WithMany()
                        .HasForeignKey("MaterialUnitId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GIPManager.MounterReportUgesAL", b =>
                {
                    b.HasOne("GIPManager.Contract", "Contract")
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GIPManager.NetRegion", "NetRegion")
                        .WithMany()
                        .HasForeignKey("NetRegionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GIPManager.ReportState", "ReportState")
                        .WithMany()
                        .HasForeignKey("ReportStateId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GIPManager.Worker", "Worker")
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GIPManager.MounterReportUgesDeviceItem", b =>
                {
                    b.HasOne("GIPManager.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GIPManager.KDE", "KDE")
                        .WithMany("MounterReportUgesDeviceItems")
                        .HasForeignKey("KDEId");

                    b.HasOne("GIPManager.Worker", "Worker")
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GIPManager.NetRegion", b =>
                {
                    b.HasOne("GIPManager.Contract", "Contract")
                        .WithMany("NetRegions")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GIPManager.NetRegionAction", b =>
                {
                    b.HasOne("GIPManager.ActionType", "ActionType")
                        .WithMany()
                        .HasForeignKey("ActionTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GIPManager.NetRegion", "NetRegion")
                        .WithMany("NetRegionActions")
                        .HasForeignKey("NetRegionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GIPManager.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GIPManager.PPEDelivery", b =>
                {
                    b.HasOne("GIPManager.DeliveryAct", "DeliveryAct")
                        .WithMany("PPEDeliveries")
                        .HasForeignKey("DeliveryActId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GIPManager.PPE", "PPE")
                        .WithOne("PEDeliveries")
                        .HasForeignKey("GIPManager.PPEDelivery", "PPEId");
                });

            modelBuilder.Entity("GIPManager.PaymentReport", b =>
                {
                    b.HasOne("GIPManager.Worker", "Worker")
                        .WithMany("PaymentReports")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GIPManager.PaymentReportRegPoint", b =>
                {
                    b.HasOne("GIPManager.PaymentReport", "PaymentReport")
                        .WithMany("PaymentReportRegPoints")
                        .HasForeignKey("PaymentReportId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GIPManager.RegPoint", "RegPoint")
                        .WithMany("PaymentReportRegPoints")
                        .HasForeignKey("RegPointId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GIPManager.PowerLineSupport", b =>
                {
                    b.HasOne("GIPManager.MounterReportUgesAL", "MounterReportUgesAL")
                        .WithMany("PowerLineSupports")
                        .HasForeignKey("MounterReportUgesALId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GIPManager.RegPoint", b =>
                {
                    b.HasOne("GIPManager.Device", "Device")
                        .WithMany("RegPoints")
                        .HasForeignKey("DeviceId");

                    b.HasOne("GIPManager.Substation", "Substation")
                        .WithMany("RegPoints")
                        .HasForeignKey("SubstationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GIPManager.RegPointAction", b =>
                {
                    b.HasOne("GIPManager.ActionType", "ActionType")
                        .WithMany()
                        .HasForeignKey("ActionTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GIPManager.RegPoint", "RegPoint")
                        .WithMany("RegPointActions")
                        .HasForeignKey("RegPointId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GIPManager.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GIPManager.RegPointFlags", b =>
                {
                    b.HasOne("GIPManager.RegPoint", "RegPoint")
                        .WithOne("RegPointFlags")
                        .HasForeignKey("GIPManager.RegPointFlags", "RegPointId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GIPManager.ReportComment", b =>
                {
                    b.HasOne("GIPManager.ReportType", "ReportType")
                        .WithMany()
                        .HasForeignKey("ReportTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GIPManager.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GIPManager.ReportRemark", b =>
                {
                    b.HasOne("GIPManager.ReportType", "ReportType")
                        .WithMany()
                        .HasForeignKey("ReportTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GIPManager.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GIPManager.SBReport", b =>
                {
                    b.HasOne("GIPManager.Contract", "Contract")
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GIPManager.NetRegion", "NetRegion")
                        .WithMany()
                        .HasForeignKey("NetRegionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GIPManager.ReportState", "ReportState")
                        .WithMany()
                        .HasForeignKey("ReportStateId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GIPManager.Worker", "Worker")
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GIPManager.Substation", b =>
                {
                    b.HasOne("GIPManager.NetRegion", "NetRegion")
                        .WithMany("Substations")
                        .HasForeignKey("NetRegionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GIPManager.SubstationState", "SubstationState")
                        .WithMany("Substation")
                        .HasForeignKey("SubstationStateId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GIPManager.SubstationAction", b =>
                {
                    b.HasOne("GIPManager.ActionType", "ActionType")
                        .WithMany()
                        .HasForeignKey("ActionTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GIPManager.Substation", "Substation")
                        .WithMany("SubstationActions")
                        .HasForeignKey("SubstationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GIPManager.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GIPManager.SubstationDevice", b =>
                {
                    b.HasOne("GIPManager.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GIPManager.Substation", "Substation")
                        .WithMany()
                        .HasForeignKey("SubstationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GIPManager.SubstationLink", b =>
                {
                    b.HasOne("GIPManager.Substation", "Substation")
                        .WithMany("SubstationLinks")
                        .HasForeignKey("SubstationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GIPManager.Switch", b =>
                {
                    b.HasOne("GIPManager.SBReport", "SBReport")
                        .WithMany("Switches")
                        .HasForeignKey("SBReportId");

                    b.HasOne("GIPManager.USPDReport", "USPDReport")
                        .WithMany("Switches")
                        .HasForeignKey("USPDReportId");
                });

            modelBuilder.Entity("GIPManager.USPDReport", b =>
                {
                    b.HasOne("GIPManager.Contract", "Contract")
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GIPManager.NetRegion", "NetRegion")
                        .WithMany()
                        .HasForeignKey("NetRegionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GIPManager.ReportState", "ReportState")
                        .WithMany()
                        .HasForeignKey("ReportStateId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GIPManager.Worker", "Worker")
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GIPManager.UnmountReport", b =>
                {
                    b.HasOne("GIPManager.Contract", "Contract")
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GIPManager.ReportState", "ReportState")
                        .WithMany()
                        .HasForeignKey("ReportStateId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GIPManager.Worker", "Worker")
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GIPManager.UnmountedDevice", b =>
                {
                    b.HasOne("GIPManager.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GIPManager.UnmountReport", "UnmountReport")
                        .WithMany("UnmountedDevices")
                        .HasForeignKey("UnmountReportId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GIPManager.UnreadSubstationComment", b =>
                {
                    b.HasOne("GIPManager.CommentSubstation", "CommentSubstation")
                        .WithMany()
                        .HasForeignKey("CommentSubstationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GIPManager.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GIPManager.User", b =>
                {
                    b.HasOne("GIPManager.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId");
                });

            modelBuilder.Entity("GIPManager.Worker", b =>
                {
                    b.HasOne("GIPManager.WorkerType", "WorkerType")
                        .WithMany("Workers")
                        .HasForeignKey("WorkerTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
